### ISSUE TITLE
account holding instead of wallet balance

### ISSUE THREAD

**Issue by ravisser** [melonproject/portal#305] opened 2017-07-03 17:06 UTC
A tx error occured, the 0.93 eth in the transaction somehow got placed in account holding instead of wallet.
How can is get in in the wallet and out of account holding

Account Holdings
Asset
(Name)

Quantity
(#)

Price
(EUR)

Change 24h
(%)

Bitcoin Token (BTC-T)	0.0000	2,255.9091	-1.9590
Ether Token (ETH-T)	0.9300	248.1500	±0.0
Euro Token (EUR-T)	0.0000	1.0005	1.8645
Melon Token (MLN)	0.0000	61.7289	-0.3225
Rep Token (REP)	0.0000	24.9397	0.0979

**Comment by jennazenk** [comment] 2017-07-27 08:35
I'm closing this since it is expected behavior. When invest in a fund fails, k-eth gets transformed into Ether Token and are available under My Account Holdings. Could be retrieved by calling the `withdraw()` function on the Ether Token Contract. Probably should implement this functionnality on portal, so I'm opening a new issue (#348) for this.

**Closed by jennazenk** 2017-07-27 08:35 UTC
