### ISSUE TITLE
Redeem not showing Ether in account

### ISSUE THREAD

**Issue by perhamgirl** [melonproject/portal#260] opened 2017-06-16 14:13 UTC
from an asset manager in gVA:  redemption led to selling holdings pro-rata but the overall AUM took time to adjust so % holdings were off for a moment. It is interesting to fil redemption with automatic selling but it could be a problem, should redemptions be blocked if there is no ETH, I do not know. If crypto assets are liquid enough then your approach is great, if not....

have informed that this is the invest/redeem mechanism (slice) - pls confirm correct reason. thx!

**Comment by jennazenk** [comment] 2017-06-20 10:54
(i) Redeem process 
When you redeem shares of your fund, a pro rata of the fund’s holdings is calculated based on the number of shares you wish to redeem. This pro rata will be transferred from the fund to your account ('My Account’ tab). If a fund holds 3 ETH-T, 3 MLN-T and 3 BTC-T, and you want to redeem 1 share, your updated account holdings will be 1 ETH-T, 1 MLN-T and 1 BTC-T. 

(ii) Difference between K-ETH and ETH-T
K-ETH and ETH-T are 2 inherently different tokens. K-ETH represents test ether on the Kovan network. As of now, the Melon Protocol is built such as a Melon fund can only hold ERC20 tokens. The problem is that K-ETH is not an ERC20 token. So we had to design/build an abstraction of test ether on the Kovan network in a ERC20 format: the ETH-T (or Ether Token Contract). This ETH-T can be held by your fund, just as any other ERC20 token. Consequently, when you redeem shares of your fund, the fund will only be able to transfer you ERC20 tokens; so if the fund had 10 ETH-T, and you wish to redeem 2 shares, your account will receive 2 ETH-T (and not 2 K-ETH). ETH-T (Ether Token Contract) is a contract asset built by Melonport for test purposes; therefore ETH-T holdings are not supported by Metamask, they can only be seen under the Account Holdings section, on the « My Account » tab. However, one can always convert his ETH-T into K-ETH by calling the corresponding function on the Ether Token contract.

The current design is built in a way that it maximizes security and as of now it might be a bit cumbersome but we work at simplifying the redeem process for the 0.2.0 release.

**Closed by jennazenk** 2017-06-20 10:54 UTC
