### ISSUE TITLE
KETH tx's failed to complete fund investment 

### ISSUE THREAD

**Issue by bangers89** [melonproject/portal#318] opened 2017-07-10 16:12 UTC
I tried twice to invest in my own fund (Hal). The KETH tx's were processed but the AUM balance on my fund failed to update. 

These are the KETH tx's 
https://kovan.etherscan.io/tx/0x633b85cd779419f7a995acc425dd3342c749b3f811f7b3117ff066ec261ed3e4
https://kovan.etherscan.io/tx/0x7163351175d00f221ec0ab3ee11f2fa5b2d81e723603959bcec751a373e1234c

Since then, George Hallam sent a funding tx and it did show up straight away so not sure if it's a local issue.

**Comment by jennazenk** [comment] 2017-07-10 16:35
Hello @bangers89 
Was that your first invesment attempt in your fund? If so, did you accept the 3 metamask popups?

**Comment by thehighfiveghost** [comment] 2017-07-11 09:09
I believe it only had 2 metamask popups.

**Comment by bangers89** [comment] 2017-07-11 13:14
Thanks guys. Yes, I believe I only got to metamask popups or (as is more likely) I was being stupid and missed one. either way, I agree they should automatically re-credited if user fails to complete full process:)

**Comment by jennazenk** [comment] 2017-07-11 13:52
The k-eth is not lost in the system, it is credited in your account holdings as Ether Token. One could retrieve it by calling the corresponding function on the Ether Token Contract to convert it back into Kovan Ether. It is indeed something that can be implemented in future versions. Long term vision, user will not be confronted with that anyway since the investment process should become less cumbersome. I'll close this one since the issue is opened here #266

**Closed by jennazenk** 2017-07-11 13:52 UTC
